// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaFX4YTCkPP_iSzZhtk65cTjeH1UJUwBQ',
    appId: '1:523264101537:web:70981cdaa1923ad1f334e0',
    messagingSenderId: '523264101537',
    projectId: 'rimio-190cd',
    authDomain: 'rimio-190cd.firebaseapp.com',
    storageBucket: 'rimio-190cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbt-xbVKnUQu59PI4G-KdAU9ZsXff4BVg',
    appId: '1:523264101537:android:1d0f664fc99c0a10f334e0',
    messagingSenderId: '523264101537',
    projectId: 'rimio-190cd',
    storageBucket: 'rimio-190cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV_ALKH7FRfmCeKx-aWkgBn-FU92um4cg',
    appId: '1:523264101537:ios:3bd7f0b146152d7ff334e0',
    messagingSenderId: '523264101537',
    projectId: 'rimio-190cd',
    storageBucket: 'rimio-190cd.appspot.com',
    androidClientId: '523264101537-8lv0tukqqderecrkhkd00dud6sd4kp64.apps.googleusercontent.com',
    iosClientId: '523264101537-im37j9udfiatsmi2uk220hvsil3ibrpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV_ALKH7FRfmCeKx-aWkgBn-FU92um4cg',
    appId: '1:523264101537:ios:b88562de34de8384f334e0',
    messagingSenderId: '523264101537',
    projectId: 'rimio-190cd',
    storageBucket: 'rimio-190cd.appspot.com',
    androidClientId: '523264101537-8lv0tukqqderecrkhkd00dud6sd4kp64.apps.googleusercontent.com',
    iosClientId: '523264101537-22c33dd7hbg8obj0fi6035lluht9ln08.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicMarket.RunnerTests',
  );
}
